/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'math' : IDL.Null,
  'chemistry' : IDL.Null,
  'physics' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserProgress = IDL.Record({
  'solvedQuestions' : IDL.Record({
    'math' : IDL.Nat,
    'chemistry' : IDL.Nat,
    'physics' : IDL.Nat,
  }),
  'weakTopics' : IDL.Vec(IDL.Text),
  'solvedQuestionIds' : IDL.Vec(IDL.Nat),
  'practiceStreakDays' : IDL.Nat,
  'accuracy' : IDL.Record({
    'math' : IDL.Nat,
    'chemistry' : IDL.Nat,
    'physics' : IDL.Nat,
  }),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'subject' : Subject,
  'difficulty' : Difficulty,
  'questionText' : IDL.Text,
  'solutionText' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func(
      [Subject, IDL.Text, Difficulty, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProgress))],
      ['query'],
    ),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
  'getQuestionsByDifficulty' : IDL.Func(
      [Difficulty],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsBySubject' : IDL.Func([Subject], [IDL.Vec(Question)], ['query']),
  'getQuestionsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'solveQuestion' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'solveQuestionWithImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProgress' : IDL.Func(
      [
        IDL.Record({
          'math' : IDL.Nat,
          'chemistry' : IDL.Nat,
          'physics' : IDL.Nat,
        }),
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Record({
          'math' : IDL.Nat,
          'chemistry' : IDL.Nat,
          'physics' : IDL.Nat,
        }),
        IDL.Vec(IDL.Nat),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'math' : IDL.Null,
    'chemistry' : IDL.Null,
    'physics' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserProgress = IDL.Record({
    'solvedQuestions' : IDL.Record({
      'math' : IDL.Nat,
      'chemistry' : IDL.Nat,
      'physics' : IDL.Nat,
    }),
    'weakTopics' : IDL.Vec(IDL.Text),
    'solvedQuestionIds' : IDL.Vec(IDL.Nat),
    'practiceStreakDays' : IDL.Nat,
    'accuracy' : IDL.Record({
      'math' : IDL.Nat,
      'chemistry' : IDL.Nat,
      'physics' : IDL.Nat,
    }),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'subject' : Subject,
    'difficulty' : Difficulty,
    'questionText' : IDL.Text,
    'solutionText' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func(
        [Subject, IDL.Text, Difficulty, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProgress))],
        ['query'],
      ),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
    'getQuestionsByDifficulty' : IDL.Func(
        [Difficulty],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsBySubject' : IDL.Func(
        [Subject],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'solveQuestion' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'solveQuestionWithImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProgress' : IDL.Func(
        [
          IDL.Record({
            'math' : IDL.Nat,
            'chemistry' : IDL.Nat,
            'physics' : IDL.Nat,
          }),
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Record({
            'math' : IDL.Nat,
            'chemistry' : IDL.Nat,
            'physics' : IDL.Nat,
          }),
          IDL.Vec(IDL.Nat),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };