/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Question {
  'id' : bigint,
  'topic' : string,
  'subject' : Subject,
  'difficulty' : Difficulty,
  'questionText' : string,
  'solutionText' : string,
}
export type Subject = { 'math' : null } |
  { 'chemistry' : null } |
  { 'physics' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProgress {
  'solvedQuestions' : {
    'math' : bigint,
    'chemistry' : bigint,
    'physics' : bigint,
  },
  'weakTopics' : Array<string>,
  'solvedQuestionIds' : Array<bigint>,
  'practiceStreakDays' : bigint,
  'accuracy' : { 'math' : bigint, 'chemistry' : bigint, 'physics' : bigint },
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addQuestion' : ActorMethod<
    [Subject, string, Difficulty, string, string],
    undefined
  >,
  'getAllProgress' : ActorMethod<[], Array<[Principal, UserProgress]>>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getProgress' : ActorMethod<[Principal], UserProgress>,
  'getQuestionsByDifficulty' : ActorMethod<[Difficulty], Array<Question>>,
  'getQuestionsBySubject' : ActorMethod<[Subject], Array<Question>>,
  'getQuestionsByTopic' : ActorMethod<[string], Array<Question>>,
  'solveQuestion' : ActorMethod<[string, string, string], string>,
  'solveQuestionWithImage' : ActorMethod<[string, string, string, string, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProgress' : ActorMethod<
    [
      { 'math' : bigint, 'chemistry' : bigint, 'physics' : bigint },
      Array<string>,
      bigint,
      { 'math' : bigint, 'chemistry' : bigint, 'physics' : bigint },
      Array<bigint>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];